name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main  # 或你用于部署的其他分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{secrets.GCP_PROJECT_ID}}
        service_account_key: ${{secrets.GCP_SA_KEY}}
        export_default_credentials: true

    - name: Upload HTML files
      run: gsutil cp *.html gs://chai_assignment5

    - name: Upload CSS files
      run: gsutil cp *.css gs://chai_assignment5

    - name: Upload JavaScript files
      run: gsutil cp *.js gs://chai_assignment5
