name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main  # 触发部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest  # 工作流运行环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 检出代码

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2  # 设置Google Cloud SDK
      with:
        version: '>= 363.0.0'

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: 'projects/843789271227/locations/global/workloadIdentityPools/assignment5/providers/github-actions'
        service_account: 'chaisj15@gmail.com'
        create_credentials_file: true  # 创建GCP凭证文件

    - name: Upload files to Google Cloud Storage
      run: |
        gsutil cp ./path/to/your/files gs://chai_assignment5/
